version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "8080:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "80:80"
          - "443:443"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=db_test"
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=root123
      volumes:
          - ./database:/var/lib/mysql
